init:
# Uncomment to get the rdp login for the build agent
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.autocrlf input
  - git config --global push.default simple

version: 1.0.{build}

build_script:
- cmd: "build.cmd All"




# uncomment to debug will stop the build server for 1 hour
#on_finish:
#- cmd: pause
